# Generated by Django 6.0.3 on 2026-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
