# Generated by Django 6.0.3 on 2026-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_story_expires_at_alter_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
    ]
